---
# tasks file for atb-ansible-nfsmount
- name: Install nfs-common
  ansible.builtin.apt:
    name: nfs-common
    update_cache: true
    install_recommends: true

- name: Add Share
  block:
    - name: create directory
      ansible.builtin.file:
        state: directory
        path: "{{ item.dir }}"
      with_items: "{{nfsmount_shares}}"
    - name: create mount
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "{{item.host}}:{{item.export}} {{item.dir}} nfs4 {{item.opts|default('defaults')}} 0 0"
        create: yes
      with_items: "{{nfsmount_shares}}"

